"use strict";Object.defineProperty(exports, "__esModule", {value: true}); function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }var _react = __r(1); var _react2 = _interopRequireDefault(_react);
var _reactdom = __r(4);
var _ui = __r(8);
var _profile = __r(16);
var _Icon = __r(9); var _Icon2 = _interopRequireDefault(_Icon);
 function Dialog({ title, onClose, children, className='' }) {
  _ui.useScrollLock.call(void 0, );const ref=_ui.useDialogFocus.call(void 0, onClose);
  return _reactdom.createPortal.call(void 0, _react2.default.createElement('div', { className: "dialog-backdrop", onClick: e=>{if(e.target===e.currentTarget)onClose();},}, _react2.default.createElement('div', { className: `dialog-panel ${className}`, ref: ref, role: "dialog", 'aria-modal': "true", 'aria-label': title,}, _react2.default.createElement('div', { className: "dialog-header",}, _react2.default.createElement('span', { className: "eyebrow",}, title), _react2.default.createElement('button', { className: "round-button", 'aria-label': "关闭对话框", onClick: onClose,}, _react2.default.createElement(_Icon2.default, { name: "close",}))), children)),document.body);
} exports.Dialog = Dialog;
 function ContactDialog({ onClose, initialType='品牌与平面设计', initialIdea='' }) {
  const [name,setName]=_react.useState.call(void 0, ''),[email,setEmail]=_react.useState.call(void 0, ''),[type,setType]=_react.useState.call(void 0, initialType),[idea,setIdea]=_react.useState.call(void 0, initialIdea),[status,setStatus]=_react.useState.call(void 0, '');
  const text=()=>`致 ${_profile.profile.name}：\n\n你好，我是 ${name.trim()||'一位新的合作伙伴'}。\n合作方向：${type}\n需求：${idea.trim()||'希望进一步沟通合作的可能。'}\n回复邮箱：${email.trim()||'待补充'}\n\n期待交流。`;
  const submit=async e=>{e.preventDefault();const copied=await _ui.copyText.call(void 0, text());setStatus(copied?'合作邀约已复制。未发送任何邮件。':'自动复制未获授权。请选中下方文本手动复制。');};
  return _react2.default.createElement(Dialog, { title: "CONTACT / 合作邀约"  , onClose: onClose,}, _react2.default.createElement('h2', null, "把你的想法", _react2.default.createElement('br', null ), _react2.default.createElement('em', null, "带进下一帧。")), _react2.default.createElement('form', { onSubmit: submit, className: "contact-form",}, _react2.default.createElement('div', { className: "form-row",}, _react2.default.createElement('label', null, "你的称呼", _react2.default.createElement('input', { autoComplete: "name", value: name, onChange: e=>setName(e.target.value), placeholder: "怎么称呼你",})), _react2.default.createElement('label', null, "回复邮箱", _react2.default.createElement('input', { type: "email", autoComplete: "email", value: email, onChange: e=>setEmail(e.target.value), placeholder: "you@example.com",}))), _react2.default.createElement('label', null, "合作方向", _react2.default.createElement('select', { value: type, onChange: e=>setType(e.target.value),}, [..._profile.profile.skills,'其他创意合作'].map(v=>_react2.default.createElement('option', { key: v,}, v)))), _react2.default.createElement('label', null, "简单说说你的想法", _react2.default.createElement('textarea', { rows: "3", value: idea, onChange: e=>setIdea(e.target.value), placeholder: "项目背景、内容、时间安排……",})), _react2.default.createElement('div', { className: "form-actions",}, _react2.default.createElement('button', { type: "submit", className: "primary-button",}, "复制合作邀约 " , _react2.default.createElement(_Icon2.default, { name: "copy",})), _profile.profile.email&&_react2.default.createElement('a', { className: "text-button", href: `mailto:${_profile.profile.email}?subject=${encodeURIComponent(`作品集合作邀约 · ${type}`)}&body=${encodeURIComponent(text())}`,}, "打开邮件草稿 " , _react2.default.createElement(_Icon2.default, { name: "mail",}))))
    , _react2.default.createElement('p', { className: "content-note",}, _profile.profile.email?`收件人：${_profile.profile.email}。表单内容仅用于生成你的邮件草稿。`:'尚未配置收件邮箱。此处可以整理并复制邀约，不会上传或发送表单内容。'), _react2.default.createElement('p', { className: "action-status", 'aria-live': "polite",}, status), status.includes('手动')&&_react2.default.createElement('textarea', { className: "copy-fallback", readOnly: true, value: text(), onFocus: e=>e.target.select(),}));
} exports.ContactDialog = ContactDialog;
 function ResumeDialog({ onClose }) {
  const summary=`${_profile.profile.name}\n${_profile.profile.title}\n\n能力方向\n${_profile.profile.skills.map(s=>'— '+s).join('\n')}\n\n作品类型\n公众号视觉内容、品牌与平面设计、影像与创意实验。\n\n说明\n这是根据原项目内容整理的作品与能力摘要，不是完整任职简历。正式经历和联系方式尚待本人补充。`;
  return _react2.default.createElement(Dialog, { title: "PROFILE / 个人能力档案"  , onClose: onClose,}, _react2.default.createElement('h2', null, "KILIAN", _react2.default.createElement('br', null ), _react2.default.createElement('em', null, "ZHOU.")), _react2.default.createElement('p', { className: "profile-title",}, _profile.profile.title), _react2.default.createElement('div', { className: "profile-skills",}, _profile.profile.skills.map((s,i)=>_react2.default.createElement('div', { key: s,}, _react2.default.createElement('small', null, "0", i+1), _react2.default.createElement('span', null, s), _react2.default.createElement(_Icon2.default, { name: "diagonal",})))), _react2.default.createElement('p', { className: "content-note",}, "正式简历文件、任职信息与联系方式尚未提供。以下导出的是作品与能力摘要，不会将原站的项目示例冒充完整履历。"), _react2.default.createElement('div', { className: "form-actions",}, _react2.default.createElement('button', { className: "primary-button", onClick: ()=>_ui.downloadText.call(void 0, 'Kilian_Zhou_Profile.txt',summary),}, "导出能力摘要 " , _react2.default.createElement(_Icon2.default, { name: "download",})), _profile.profile.resumeUrl?_react2.default.createElement('a', { className: "text-button", href: _profile.profile.resumeUrl, download: true,}, "下载完整简历 " , _react2.default.createElement(_Icon2.default, { name: "download",})):_react2.default.createElement('span', { className: "resume-pending",}, "完整简历待上传")));
} exports.ResumeDialog = ResumeDialog;
